import React from 'react'
import { ArrowLeft, Save, Zap, ChevronDown } from 'lucide-react'
import { useStore } from '../store/useStore'
import type { PortForwardFormData } from '../types'

const GROUPS = ['Services', 'Databases', 'Dashboards', 'Monitoring', 'Other']

export default function PortForwardFormView() {
  const { view, editingPf, setView, addPortForward, updatePortForward } = useStore()
  const isEdit = view === 'pf-edit'

  const [form, setForm] = React.useState<PortForwardFormData>({
    name:        editingPf?.name        ?? '',
    group_name:  editingPf?.group_name  ?? 'Services',
    namespace:   editingPf?.namespace   ?? '',
    service:     editingPf?.service     ?? '',
    local_port:  editingPf?.local_port  ?? 4000,
    remote_port: editingPf?.remote_port ?? 80,
    command:     editingPf?.command     ?? '',
  })

  const [errors, setErrors] = React.useState<Partial<Record<keyof PortForwardFormData, string>>>({})
  const [saving, setSaving] = React.useState(false)
  const [autoGenerated, setAutoGenerated] = React.useState(false)

  const buildCommand = (f: typeof form) =>
    `kubectl -n ${f.namespace} port-forward service/${f.service} ${f.local_port}:${f.remote_port}`

  const parseCommand = (cmd: string) => {
    const updated = { ...form }
    
    // Match: kubectl -n NAMESPACE port-forward service/SERVICE LOCAL:REMOTE
    const nsMatch = cmd.match(/-n\s+(\S+)/)
    const serviceMatch = cmd.match(/service\/(\S+)/)
    const portsMatch = cmd.match(/(\d+):(\d+)/)
    
    if (nsMatch) updated.namespace = nsMatch[1]
    if (serviceMatch) updated.service = serviceMatch[1]
    if (portsMatch) {
      updated.local_port = parseInt(portsMatch[1])
      updated.remote_port = parseInt(portsMatch[2])
    }
    
    return updated
  }

  const handleChange = (field: keyof PortForwardFormData, value: string | number) => {
    const updated = { ...form, [field]: value }
    if (['namespace', 'service', 'local_port', 'remote_port'].includes(field)) {
      updated.command = buildCommand(updated)
      setAutoGenerated(true)
    }
    if (field === 'namespace' && !form.name) updated.name = String(value)
    setForm(updated)
    setErrors(e => ({ ...e, [field]: undefined }))
  }

  const validate = () => {
    const e: typeof errors = {}
    if (!form.name.trim())      e.name = 'Required'
    if (!form.namespace.trim()) e.namespace = 'Required'
    if (!form.service.trim())   e.service = 'Required'
    if (!form.command.trim())   e.command = 'Required'
    if (!form.local_port)       e.local_port = 'Required'
    if (!form.remote_port)      e.remote_port = 'Required'
    return e
  }

  const handleSave = async () => {
    const errs = validate()
    if (Object.keys(errs).length > 0) { setErrors(errs); return }
    setSaving(true)
    try {
      if (isEdit && editingPf) {
        const updated = await window.api.pf.update(editingPf.id, form)
        updatePortForward(updated)
      } else {
        const created = await window.api.pf.create(form)
        addPortForward(created)
      }
      setView('pf-manage')
    } finally {
      setSaving(false)
    }
  }

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }} className="animate-fade">
      <div style={{ padding: '14px 22px', borderBottom: '1px solid var(--border)', background: 'var(--bg-panel)', display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 }}>
        <button onClick={() => setView('pf-manage')}
          onMouseEnter={e => e.currentTarget.style.color = 'var(--text-primary)'}
          onMouseLeave={e => e.currentTarget.style.color = 'var(--text-muted)'}
          style={{ display: 'flex', alignItems: 'center', gap: 5, background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', fontSize: 11, fontFamily: 'var(--font-mono)', padding: '4px 0' }}>
          <ArrowLeft size={13} /> Back
        </button>
        <div style={{ width: 1, height: 14, background: 'var(--border)' }} />
        <div>
          <div style={{ fontSize: 9, color: 'var(--text-muted)', letterSpacing: '0.12em', textTransform: 'uppercase' }}>{isEdit ? 'Edit Port-Forward' : 'New Port-Forward'}</div>
          <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 15 }}>{isEdit ? editingPf?.name : 'Configure a service tunnel'}</div>
        </div>
      </div>

      <div style={{ flex: 1, overflowY: 'auto', padding: 22 }}>
        <div style={{ maxWidth: 600, display: 'flex', flexDirection: 'column', gap: 20 }}>

          <Section title="Identity" subtitle="Name and group for this service">
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
              <Field label="Name" error={errors.name} required>
                <Input value={form.name} onChange={v => handleChange('name', v)} placeholder="e.g. core-entities-service" error={!!errors.name} />
              </Field>
              <Field label="Group">
                <SelectField value={form.group_name} onChange={v => handleChange('group_name', v)} options={GROUPS} />
              </Field>
            </div>
          </Section>

          <Section title="Kubernetes Target" subtitle="Namespace, service, and ports">
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
              <Field label="Namespace" error={errors.namespace} required>
                <Input value={form.namespace} onChange={v => handleChange('namespace', v)} placeholder="e.g. core-entities" error={!!errors.namespace} />
              </Field>
              <Field label="Service" error={errors.service} required>
                <Input value={form.service} onChange={v => handleChange('service', v)} placeholder="e.g. core-entities" error={!!errors.service} />
              </Field>
              <Field label="Local Port" error={errors.local_port ? String(errors.local_port) : undefined} required>
                <Input value={String(form.local_port)} onChange={v => handleChange('local_port', parseInt(v) || 0)} placeholder="4010" error={!!errors.local_port} mono />
              </Field>
              <Field label="Remote Port" error={errors.remote_port ? String(errors.remote_port) : undefined} required>
                <Input value={String(form.remote_port)} onChange={v => handleChange('remote_port', parseInt(v) || 0)} placeholder="80" error={!!errors.remote_port} mono />
              </Field>
            </div>
          </Section>

          <Section title="kubectl Command"
            subtitle="Executed to start the tunnel"
            action={
              <button onClick={() => { handleChange('command', buildCommand(form)); setAutoGenerated(true) }}
                style={{ display: 'flex', alignItems: 'center', gap: 4, background: 'var(--accent-green-dim)', border: '1px solid var(--accent-green)', color: 'var(--accent-green)', borderRadius: 3, padding: '3px 9px', fontSize: 10, fontFamily: 'var(--font-mono)', cursor: 'pointer' }}>
                <Zap size={10} /> Auto-generate
              </button>
            }>
            {autoGenerated && <div style={{ fontSize: 10, color: 'var(--accent-green)', marginBottom: 7, display: 'flex', alignItems: 'center', gap: 4 }}><Zap size={10} /> Generated from namespace/service/ports above</div>}
            <Field label="" error={errors.command}>
              <textarea value={form.command} onChange={e => { 
                const parsed = parseCommand(e.target.value)
                setForm(parsed)
                setAutoGenerated(false)
                setErrors(err => ({ ...err, command: undefined }))
              }} rows={2} spellCheck={false}
                style={{ width: '100%', background: 'var(--bg-input)', border: `1px solid ${errors.command ? 'var(--accent-red)' : 'var(--border)'}`, borderRadius: 4, color: 'var(--accent-amber)', fontFamily: 'var(--font-mono)', fontSize: 11, padding: '8px 11px', outline: 'none', resize: 'vertical', lineHeight: 1.6 }}
                onFocus={e => e.currentTarget.style.borderColor = 'var(--border-active)'}
                onBlur={e => e.currentTarget.style.borderColor = errors.command ? 'var(--accent-red)' : 'var(--border)'} />
            </Field>
          </Section>
        </div>
      </div>

      <div style={{ padding: '12px 22px', borderTop: '1px solid var(--border)', background: 'var(--bg-panel)', display: 'flex', justifyContent: 'flex-end', gap: 10, flexShrink: 0 }}>
        <button onClick={() => setView('pf-manage')} style={{ padding: '7px 18px', background: 'transparent', border: '1px solid var(--border)', borderRadius: 4, color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)', fontSize: 11, cursor: 'pointer' }}>Cancel</button>
        <button onClick={handleSave} disabled={saving}
          style={{ padding: '7px 20px', background: saving ? 'var(--bg-elevated)' : 'var(--accent-green)', border: 'none', borderRadius: 4, color: saving ? 'var(--text-muted)' : '#0d0f12', fontFamily: 'var(--font-mono)', fontWeight: 700, fontSize: 11, cursor: saving ? 'not-allowed' : 'pointer', display: 'flex', alignItems: 'center', gap: 7 }}>
          <Save size={12} /> {saving ? 'Saving...' : isEdit ? 'Save Changes' : 'Create'}
        </button>
      </div>
    </div>
  )
}

function Section({ title, subtitle, children, action }: { title: string; subtitle?: string; children: React.ReactNode; action?: React.ReactNode }) {
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
        <div>
          <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 13, color: 'var(--text-primary)' }}>{title}</div>
          {subtitle && <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 2 }}>{subtitle}</div>}
        </div>
        {action}
      </div>
      <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 8, padding: 14 }}>{children}</div>
    </div>
  )
}

function Field({ label, error, required, children }: { label: string; error?: string; required?: boolean; children: React.ReactNode }) {
  return (
    <div>
      {label && <div style={{ fontSize: 9, color: 'var(--text-muted)', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 5 }}>{label}{required && <span style={{ color: 'var(--accent-red)', marginLeft: 3 }}>*</span>}</div>}
      {children}
      {error && <div style={{ fontSize: 10, color: 'var(--accent-red)', marginTop: 3 }}>{error}</div>}
    </div>
  )
}

function Input({ value, onChange, placeholder, error, mono }: { value: string; onChange: (v: string) => void; placeholder?: string; error?: boolean; mono?: boolean }) {
  const [focused, setFocused] = React.useState(false)
  return (
    <input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}
      style={{ width: '100%', background: 'var(--bg-input)', border: `1px solid ${error ? 'var(--accent-red)' : focused ? 'var(--border-active)' : 'var(--border)'}`, borderRadius: 4, color: 'var(--text-primary)', fontFamily: mono ? 'var(--font-mono)' : 'var(--font-mono)', fontSize: 12, padding: '7px 10px', outline: 'none', transition: 'border-color 0.15s' }}
      onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} />
  )
}

function SelectField({ value, onChange, options }: { value: string; onChange: (v: string) => void; options: string[] }) {
  return (
    <div style={{ position: 'relative' }}>
      <select value={value} onChange={e => onChange(e.target.value)}
        style={{ width: '100%', appearance: 'none', background: 'var(--bg-input)', border: '1px solid var(--border)', borderRadius: 4, color: 'var(--text-primary)', fontFamily: 'var(--font-mono)', fontSize: 12, padding: '7px 30px 7px 10px', outline: 'none', cursor: 'pointer' }}>
        {options.map(o => <option key={o} value={o}>{o}</option>)}
      </select>
      <ChevronDown size={11} color="var(--text-muted)" style={{ position: 'absolute', right: 9, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
    </div>
  )
}
